/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package game.of.life;
import java.awt.Color;
import java.awt.Image;
import java.awt.Graphics;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.SwingUtilities;
/**
 *
 * @author Jack
 */
public class GOL extends javax.swing.JFrame {
    int wid = 250, hei = 100;
    boolean currentMove[][] = new boolean[hei][wid];
    boolean nextMove[][] = new boolean[hei][wid];
    boolean play;
    Image buffer;
    Graphics buff;
    int interval;
    int tim = 0;
    Timer time = new Timer();
    TimerTask task = new TimerTask(){
        public void run(){
            if(play){
                tim++;
                if(tim>=interval){
                    tim = 0;
                    for(int i = 0;i < hei;i++){
                        for(int j = 0;j < wid;j++){
                            nextMove[i][j] = decide(i,j);
                        }
                    }
                    for(int i = 0;i < hei;i++){
                        for(int j = 0;j < wid;j++){
                            currentMove[i][j] = nextMove[i][j];
                        }
                    }
                    repain();
                }
            }
        }
    };
    
    public void paint(Graphics g){
        super.paint(g);
        repain();
    }
    public GOL() {
        initComponents();
        buffer = createImage(jPanel1.getWidth(),jPanel1.getHeight());
        buff = jPanel1.getGraphics();
        set();
        repain();
        time.scheduleAtFixedRate(task, 0, 1);
    }
    
    private boolean decide(int i, int j){
        int neighbors = 0;
        for(int y = i-1;y<=i+1;y++){
            for(int x = j-1;x<=j+1;x++){
                if(y>=0 && x >=0 && y<=hei-1 && x <= wid -1){
                    if((y != i || x != j) && currentMove[y][x]) neighbors++;
                }
            }
        }
        
        if(neighbors==3) return true;
        if(currentMove[i][j] && neighbors == 2) return true;
        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        jButton1.setText("Play");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setText("200");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("100");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setText("50");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("0");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("90");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("180");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("270");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jPanel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentResized
        buffer = createImage(jPanel1.getWidth(),jPanel1.getHeight());
        buff = buffer.getGraphics();
        repain();
    }//GEN-LAST:event_jPanel1ComponentResized
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        play = !play;
        if(play) jButton1.setText("Pause");
        else jButton1.setText("Play");
        repain();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void spawn(int x, int y, boolean isLeft){
        int i = hei*y/jPanel1.getHeight();
        int j = wid*x/jPanel1.getWidth();
        if(isLeft){
            if(jTextField4.getText().equals("")){
                currentMove[i][j] = true;
            }else{
                String[] dot = jTextField4.getText().substring(1).split("\\},\\{");
                boolean[][] spawny = new boolean[hei][wid];
                for(int k = 0; k < dot.length; k++){
                    int ii = Integer.parseInt(dot[k].substring(1, dot[k].indexOf("\"", 1)));
                    String forJ = dot[k].substring(dot[k].indexOf("[") + 1, dot[k].indexOf("]"));
                    String[] individual = forJ.split(",");
                    for(int l = 0; l < individual.length; l++){
                        if(ii < hei && Integer.parseInt(individual[l]) < wid )
                            spawny[ii][Integer.parseInt(individual[l])] = true;
                    }
                }
                if(jRadioButton1.isSelected()){
                    for(int ii = 0; ii < spawny.length;ii++){
                        for(int jj = 0; jj < spawny[0].length;jj++){
                            if(i+ii < hei && j+jj < wid && spawny[ii][jj]) currentMove[i+ii][j+jj] = true;
                        }
                    }
                }
                if(jRadioButton2.isSelected()){
                    for(int ii = 0; ii < spawny.length;ii++){
                        for(int jj = 0; jj < spawny[0].length;jj++){
                            if(i-jj >= 0 && j+ii < wid && spawny[ii][jj]) currentMove[i-jj][j+ii] = true;
                        }
                    }
                }
                if(jRadioButton3.isSelected()){
                    for(int ii = 0; ii < spawny.length;ii++){
                        for(int jj = 0; jj < spawny[0].length;jj++){
                            if(i-ii >= 0 && j-jj >= 0 && spawny[ii][jj]) currentMove[i-ii][j-jj] = true;
                        }
                    }
                }
                if(jRadioButton4.isSelected()){
                    for(int ii = 0; ii < spawny.length;ii++){
                        for(int jj = 0; jj < spawny[0].length;jj++){
                            if(i+jj < hei && j-ii >= 0 && spawny[ii][jj]) currentMove[i+jj][j-ii] = true;
                        }
                    }
                }
            }
        }else{
            currentMove[i][j] = false;
        }
        
        repain();
        
    }
    
    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        spawn(evt.getX(),evt.getY(),SwingUtilities.isLeftMouseButton(evt));
    }//GEN-LAST:event_jPanel1MouseClicked
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        currentMove = new boolean[hei][wid];
        repain();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        set();
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        set();
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        set();
    }//GEN-LAST:event_jTextField3ActionPerformed
    
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        spawn(evt.getX(),evt.getY(),SwingUtilities.isLeftMouseButton(evt));
    }//GEN-LAST:event_jPanel1MouseDragged
    
    private void set(){
        if(wid != Integer.parseInt(jTextField1.getText()) ||
                hei != Integer.parseInt(jTextField2.getText())){
            wid = Integer.parseInt(jTextField1.getText());
            hei = Integer.parseInt(jTextField2.getText());
            currentMove = new boolean[hei][wid];
            nextMove = new boolean[hei][wid];
        }
        interval = Integer.parseInt(jTextField3.getText());
        repain();
    }
    
    /**
     * @param args the command line arguments
     */
    
    private void repain(){
        buff.setColor(jPanel1.getBackground());
        buff.fillRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        for(int i = 0 ; i < hei ; i++){
            for(int j = 0 ; j < wid; j++){
                if(currentMove[i][j]){
                    buff.setColor(Color.YELLOW);
                    int x = j * jPanel1.getWidth()/wid;
                    int y = i * jPanel1.getHeight()/hei;
                    buff.fillRect(x, y, jPanel1.getWidth()/wid, jPanel1.getHeight()/hei);
                }
            }
        }
        if(wid < 300 && hei < 300){
            for(int i = 1; i < wid;i++){
                int x = jPanel1.getWidth() * i / wid;
                buff.setColor(Color.BLACK);
                if(i % 10 == 0)buff.setColor(Color.white);
                buff.drawLine(x, 0, x, jPanel1.getHeight());
            }
            for(int i = 1; i < hei;i++){
                int y = jPanel1.getHeight() * i / hei;
                buff.setColor(Color.BLACK);
                if(i % 10 == 0)buff.setColor(Color.white);
                buff.drawLine(0, y, jPanel1.getWidth(), y);
            }
        }
        jPanel1.getGraphics().drawImage(buffer, 0, 0, jPanel1);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GOL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GOL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GOL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GOL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GOL().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
